<?php defined( 'BASEPATH' ) OR exit( 'No direct script access allowed' );
/** @noinspection PhpIncludeInspection */
require_once APPPATH . '/third_party/PHPExcel.php';

/**
 * Class Fwalker_excel
 *
 * @property PHPExcel_Worksheet $asheet
 */
class Fwl_excel extends PHPExcel
{
    private $asheet;
    private $col;
    private $row;

    public function __construct()
    {
        parent::__construct();

        $this->col = 0;
        $this->row = 1;
        $this->asheet = null;
    }

    public function setActiveSheetIndex( $pIndex = 0 )
    {
        $this->asheet = parent::setActiveSheetIndex( $pIndex ); // TODO: Change the autogenerated stub
        return $this->asheet;
    }

    public function setTitle( $title )
    {
        if ( $this->asheet == null ) return;

        $this->asheet->setTitle( $title );

        $this->col = 0;
        $this->row = 1;
    }

    public function setCellValueByColumnAndRow( $row, $col, $value, $align = PHPExcel_Style_Alignment::HORIZONTAL_CENTER, /** @noinspection PhpUnusedParameterInspection */
                                                $font = '맑은 고딕', /** @noinspection PhpUnusedParameterInspection */
                                                $size = 10 )
    {
        $cell = $this->asheet->setCellValueByColumnAndRow( $col, $row, $value, true );
        $cell->getStyle()->getAlignment()->setHorizontal( $align );
        /*
        $cell->getStyle()->getFont()->setName( $font );
        $cell->getStyle()->getFont()->setSize( $size );
        */

        return $cell;
    }

    public function setCellValueAutoColPos( $value, $align = PHPExcel_Style_Alignment::HORIZONTAL_CENTER )
    {
        $cell = $this->asheet->setCellValueByColumnAndRow( $this->col, $this->row, $value, true );
        $cell->getStyle()->getAlignment()->setHorizontal( $align );

        $this->col++;

        return $cell;
    }
    
    public function setCellValueAutoColPos_STR( $value, $align = PHPExcel_Style_Alignment::HORIZONTAL_CENTER )
    {
        $cell = $this->asheet->setCellValueExplicitByColumnAndRow( $this->col, $this->row, $value, PHPExcel_Cell_DataType::TYPE_STRING );
        $cell->getStyle()->getAlignment()->setHorizontal( $align );

        $this->col++;

        return $cell;
    }

    public function increase_row()
    {
        $this->row++;
        $this->col = 0;
    }

    public function set_row( $row )
    {
        $this->row = $row;
    }

    public function set_col( $col )
    {
        $this->col = $col;
    }
}
